import { EASINGS, EFFECT_CATALOG, TRANSFORM_LIMITS } from '@freemier/shared';
import { z } from 'zod';
import type { CommandDefinition } from './context.js';

const property = z.enum(['x', 'y', 'scale', 'rotation', 'opacity']);
const params = z.record(z.union([z.number().finite(), z.string(), z.boolean()]));
const clipId = z.string();
const ok = (data: Record<string, unknown>) => ({ ok: true, ...data });
export const CAPABILITIES_COMMANDS: CommandDefinition[] = [
  { name: 'editor_capabilities', title: 'Editor capabilities', description: 'Read implemented and unsupported capabilities; availability does not imply pixel-identical live preview.', inputSchema: {}, handler: async () => ok({ version: '0.2.0', editing: ['move', 'ripple_move', 'split', 'trim', 'slip', 'roll', 'duplicate', 'track_mute', 'track_lock', 'undo', 'redo'], animation: { properties: TRANSFORM_LIMITS, easing: EASINGS, time: 'clip-local seconds', evaluation: 'preceding key owns outgoing segment', maxKeysPerProperty: 256, export: 'cpu' }, effects: EFFECT_CATALOG, annotations: { markers: { commands: ['marker_add', 'marker_update', 'marker_remove', 'marker_list'], maxCount: 4096, time: 'fixed sequence seconds rounded to frames', range: [0, 86400], ripplePolicy: 'fixed', affectsRenderDuration: false } }, composition: { titles: { commands: ['font_list', 'title_add', 'title_update', 'title_remove', 'title_list'], maxCount: 64, maxCharacters: 4096, maxLines: 16, time: 'fixed frame-quantized sequence [start,end)', affectsRenderDuration: true, order: 'creation order above video', renderer: 'CPU FFmpeg drawtext to shared RGBA PNG', font: 'bundled checksummed Noto Sans Regular, OFL-1.1', scripts: 'Latin/Greek/Cyrillic; other glyphs not guaranteed', maxRasterDimension: 8192, maxRasterPixels: 33554432, style: 'static plain text; integer font/outline/box/spacing pixels; normalized aligned anchor; RGB/opacity', animatedText: false, implicitFontFallback: false }, captions: { commands: ['caption_add', 'caption_update', 'caption_remove', 'captions_list', 'captions_import', 'captions_export', 'caption_track_update'], maxCount: 256, maxCharacters: 4096, maxLines: 16, trackCount: 1, time: 'integer milliseconds [startMs,endMs)', frameCoverage: 'sequence frame timestamps inside cue; jump selects first covered frame', overlaps: 'rejected', ripplePolicy: 'fixed', durationPolicy: 'authored cue extent rounded up to frames, independent of visibility/output policy', renderer: 'same CPU RGBA glyph path as titles, above titles', import: 'explicit SRT content, atomic append/replace', export: ['burn-in', 'none', 'sidecar'], style: 'shared static track style with bundled Noto Sans', locks: 'explicit unlock before edits', unsupported: ['WebVTT', 'ASS', 'multiple tracks', 'rich text', 'animated captions', 'automatic transcription'] } }, timecode: { format: 'non-drop HH:MM:SS:FF', fractionalRate: 'nominal frame counts divided by actual fps', dropFrame: false }, limitations: ['Origin-changing split/head trim/right-side roll reject clips with keyframes or enabled fades; equivalent curve rebasing is not implemented', 'Effect preview implementation requirements are reported per effect; this API does not assert preview/export parity'], unsupported: ['speed_ramp', 'optical_flow', 'tracking', 'stabilization', 'LUT', 'GPU_effect_export', 'nested_sequences', 'adjustment_layers', 'transitions'] }) }
];
