import { addCaption, exportCaptions, importCaptions, listCaptions, removeCaption, updateCaption, updateCaptionTrack, type CaptionInput, type CaptionPatch } from '@freemier/engine';
import { z } from 'zod';
import type { CommandDefinition } from './context.js';

const cueText = z.string().min(1).max(4096);
const style = z.object({ fontId: z.literal('noto-sans').optional(), fontSize: z.number().finite().int().min(8).max(512).optional(), color: z.string().regex(/^#[0-9a-f]{6}$/i).optional(), outlineColor: z.string().regex(/^#[0-9a-f]{6}$/i).optional(), outlineWidth: z.number().finite().int().min(0).max(20).optional(), backgroundColor: z.string().regex(/^#[0-9a-f]{6}$/i).optional(), backgroundOpacity: z.number().finite().min(0).max(1).optional(), opacity: z.number().finite().min(0).max(1).optional(), padding: z.number().finite().int().min(0).max(32).optional(), x: z.number().finite().min(0).max(1).optional(), y: z.number().finite().min(0).max(1).optional(), align: z.enum(['left', 'center', 'right']).optional(), verticalAlign: z.enum(['top', 'middle', 'bottom']).optional(), lineSpacing: z.number().finite().int().min(0).max(64).optional() }).strict();
export const CAPTION_TOOLS: CommandDefinition[] = [
  { name: 'caption_add', title: 'Add subtitle cue', description: 'Add plain text at exact integer-millisecond sequence time [startMs,endMs). Cue overlaps and edits to a locked track are rejected.', inputSchema: { text: cueText, startMs: z.number().int().min(0).max(86_400_000), endMs: z.number().int().min(1).max(86_400_000) }, handler: async (a, c) => ({ ok: true, cue: addCaption(c.store, a as CaptionInput) }) },
  { name: 'caption_update', title: 'Edit subtitle cue', description: 'Update cue text or millisecond range in one undoable mutation.', inputSchema: { cueId: z.string(), text: cueText.optional(), startMs: z.number().int().min(0).max(86_400_000).optional(), endMs: z.number().int().min(1).max(86_400_000).optional() }, handler: async (a, c) => ({ ok: true, cue: updateCaption(c.store, a.cueId as string, a as CaptionPatch) }) },
  { name: 'caption_remove', title: 'Remove subtitle cue', description: 'Remove one editable subtitle cue by stable ID.', inputSchema: { cueId: z.string() }, handler: async (a, c) => { removeCaption(c.store, a.cueId as string); return { ok: true, removed: a.cueId }; } },
  { name: 'captions_list', title: 'Inspect subtitle track', description: 'Read current cues, integer-ms timing, resolved frame coverage and track lock/style state.', inputSchema: {}, handler: async (_a, c) => ({ ok: true, ...listCaptions(c.store) }) },
  { name: 'captions_import', title: 'Import SRT subtitle text', description: 'Parse explicitly supplied SRT content. Validates every cue before one atomic replace/append; does not read a path or URL.', inputSchema: { content: z.string().max(131_072), mode: z.enum(['replace', 'append']).default('replace') }, handler: async (a, c) => ({ ok: true, ...importCaptions(c.store, a.content as string, a.mode as 'replace' | 'append') }) },
  { name: 'captions_export', title: 'Export canonical SRT text', description: 'Return portable UTF-8 SRT content. Styling stays in the project.', inputSchema: {}, handler: async (_a, c) => ({ ok: true, content: exportCaptions(c.store), format: 'SRT', stylingIncluded: false }) },
  { name: 'caption_track_update', title: 'Update subtitle track', description: 'Change track label, enable/disable, shared glyph style, or explicitly unlock it. A locked track only accepts an explicit unlock.', inputSchema: { name: z.string().min(1).max(120).optional(), enabled: z.boolean().optional(), locked: z.boolean().optional(), style: style.optional() }, handler: async (a, c) => ({ ok: true, track: updateCaptionTrack(c.store, a as Parameters<typeof updateCaptionTrack>[1]) }) },
];
