import { applyEffectPreset, captureEffectPreset, getEffectPreset, importEffectPreset, inspectEffectPreset, removeEffectPreset } from '@freemier/engine';
import { EditorError, PRESET_MAX_BYTES, describeEffectPreset, type EffectPresetDocument } from '@freemier/shared';
import { promises as fs } from 'node:fs';
import { z } from 'zod';
import type { CommandDefinition } from './context.js';
import { readPresetSource as readSource } from '../library/import/presets.js';

const source = { content: z.string().optional().describe('FreeMier effect preset JSON; exactly one of content or path'), path: z.string().min(1).optional().describe('Local UTF-8 regular file, maximum 64 KiB; exactly one of path or content') };
const presetId = z.string().min(1), clipId = z.string().min(1);
const metadata = { name: z.string().min(1).max(128), description: z.string().max(4096).optional(), author: z.string().max(128).optional(), tags: z.array(z.string().min(1).max(64)).max(16).optional() };
const ok = (data: Record<string, unknown>) => ({ ok: true, ...data });

function serialized(document: EffectPresetDocument) { return JSON.stringify(document, null, 2) + '\n'; }
export const PRESET_TOOLS: CommandDefinition[] = [
  { name: 'effect_preset_inspect', title: 'Inspect portable effect preset', description: 'Parse bounded FreeMier JSON without importing. Returns normalized content identity, declared author description, settings, control schemas, CPU renderer and preview limits. Never executes scripts or vendor plugins.', inputSchema: source, handler: async (a) => ok({ preset: inspectEffectPreset(await readSource(a)) }) },
  { name: 'effect_preset_import', title: 'Import portable effect preset', description: 'Import .fmfx.json content or file into the owning project library. Validates every effect and hashes canonical content. One undo step; identical content is a no-op. Preserves author description/tags; vendor formats are unsupported.', inputSchema: source, handler: async (a, c) => { const preset = importEffectPreset(c.store, await readSource(a)); return ok({ preset: { ...preset, ...describeEffectPreset(preset.document) } }); } },
  { name: 'effect_preset_list', title: 'List imported presets', description: 'Search up to 64 imported presets by name, description, author or tags. Returns declared descriptions, hashes, control schemas and supported-renderer/preview limits.', inputSchema: { query: z.string().optional() }, handler: async (a, c) => { const query = String(a.query ?? '').toLowerCase(); return ok({ presets: (c.store.project.effectPresets ?? []).filter((p) => [p.document.name, p.document.description, p.document.author, ...p.document.tags].join(' ').toLowerCase().includes(query)).map((p) => ({ ...p, ...describeEffectPreset(p.document) })) }); } },
  { name: 'effect_preset_get', title: 'Describe imported preset', description: 'Inspect one imported preset, including its ordered effects, values, defaults/bounds, media kind, description source, dependency list and compatibility limits.', inputSchema: { presetId }, handler: async (a, c) => { const preset = getEffectPreset(c.store, a.presetId as string); return ok({ preset: { ...preset, ...describeEffectPreset(preset.document) } }); } },
  { name: 'effect_preset_export', title: 'Export portable preset', description: 'Return portable JSON for an imported preset. Optional path creates a new UTF-8 file exclusively; refuses overwriting any existing destination. No project mutation.', inputSchema: { presetId, path: z.string().min(1).optional() }, handler: async (a, c) => { const content = serialized(getEffectPreset(c.store, a.presetId as string).document); if (a.path !== undefined) { try { await fs.writeFile(a.path as string, content, { encoding: 'utf8', flag: 'wx' }); } catch { throw new EditorError('IO_ERROR', 'Unable to create preset file; destination must not already exist'); } } return ok({ content, format: 'freemier-effect-preset', ...(a.path === undefined ? {} : { path: a.path }) }); } },
  { name: 'effect_preset_capture', title: 'Capture clip effect settings', description: 'Read a selected clip stack as portable JSON with supplied name/description/author/tags. Excludes source media, effect IDs and transforms; unknown effects refuse. Does not import or mutate.', inputSchema: { clipId, ...metadata }, handler: async (a, c) => { const document = captureEffectPreset(c.store, a.clipId as string, { name: a.name as string, description: String(a.description ?? ''), author: String(a.author ?? ''), tags: a.tags as string[] | undefined ?? [] }); return ok({ content: serialized(document), preset: inspectEffectPreset(serialized(document)) }); } },
  { name: 'effect_preset_apply', title: 'Apply imported effect stack', description: 'Append or replace a matching clip stack atomically with fresh effect IDs, retaining stored effect order/enabled flags. Validates track lock/media, max 32 effects and clip-local fade extent before one undo step. Does not scale fade times.', inputSchema: { presetId, clipId, mode: z.enum(['append', 'replace']).optional() }, handler: async (a, c) => ok({ clip: applyEffectPreset(c.store, a.presetId as string, a.clipId as string, a.mode as 'append' | 'replace' | undefined) }) },
  { name: 'effect_preset_remove', title: 'Remove imported preset', description: 'Remove one preset from the owning library in one undo step. Already-applied clip effects remain independent.', inputSchema: { presetId }, handler: async (a, c) => { removeEffectPreset(c.store, a.presetId as string); return ok({ presetId: a.presetId }); } },
  {
    name: 'import_capabilities', title: 'Implemented import capabilities', description: 'Discover actual import handlers and limits. Additional formats require implemented adapters; inspect each format\'s declared limits.', inputSchema: {}, handler: async () => ok({
      imports: [
        { kind: 'effect-preset', format: 'freemier-effect-preset', version: 1, extension: '.fmfx.json', commands: PRESET_TOOLS.filter((t) => t.name.startsWith('effect_preset_')).map((t) => t.name), maxBytes: PRESET_MAX_BYTES, maxLibraryCount: 64, maxEffects: 32, externalResources: false, executablePlugins: false },
        { kind: 'captions', format: 'plain SRT', commands: ['captions_import', 'captions_list', 'captions_export'], input: 'explicit UTF-8 text', maxCues: 256, overlappingCues: false },
        { kind: 'project', format: 'FreeMier schema 1', extensions: ['.freemier', '.palmier'], command: 'project_load', input: 'project directory', limits: 'Legacy independent schema only; no proprietary Palmier project conversion' },
        { kind: 'media', command: 'media_probe', importCommand: 'media_import', compatibility: 'Actual installed ffprobe/FFmpeg decoder and stream properties; probe per file', limits: 'No promise of arbitrary camera RAW, image sequences, layered graphics or every container/codec profile' },
      ]
    })
  },
];
