/** Standard MCP calls and real Electron interactions against one owning session. */
import assert from 'node:assert/strict';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { spawn, execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { promises as fs } from 'node:fs';
import net from 'node:net';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../..');
const electron = createRequire(import.meta.url)('electron'), execute = promisify(execFile);
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function waitFor(label, fn, timeout = 20000) {
  const end = Date.now() + timeout; let last;
  while (Date.now() < end) { try { const value = await fn(); if (value) return value; } catch (error) { last = error; } await sleep(100); }
  throw new Error('Timeout: ' + label + (last ? ' ' + last.message : ''));
}
async function freePort() { const server = net.createServer(); await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve)); const port = server.address().port; await new Promise((resolve) => server.close(resolve)); return port; }
await fs.mkdir(path.join(root, '.tmp'), { recursive: true });
const workspace = await fs.mkdtemp(path.join(root, '.tmp', 'linked-gui-'));
const port = await freePort(), debugPort = await freePort(), bridge = `http://127.0.0.1:${port}`;
const saved = path.join(workspace, 'Linked project.freemier'), output = path.join(workspace, 'linked-gui.mp4');
const env = { ...process.env, FREEMIER_WORKSPACE: workspace, FREEMIER_BRIDGE_PORT: String(port), FREEMIER_TEST_MODE: '1', FREEMIER_TEST_DIALOGS: JSON.stringify({ project: saved, output }) }; delete env.ELECTRON_RUN_AS_NODE;
let client, child, socket, log = ''; const errors = [], checks = [];
const check = (name) => { checks.push(name); console.log('PASS: ' + name); };
try {
  client = new Client({ name: 'linked-electron-acceptance', version: '1' });
  await client.connect(new StdioClientTransport({ command: process.execPath, args: [path.join(root, 'packages/mcp/dist/cli.js')], env }));
  const call = async (name, args = {}) => { const response = await client.callTool({ name, arguments: args }); const value = JSON.parse(response.content[0].text); if (response.isError) throw new Error(value.error.message); return value; };
  await waitFor('bridge', async () => (await fetch(bridge + '/health')).ok);
  await call('project_create', { name: 'Linked AV acceptance', width: 320, height: 180, fps: 30 });
  const asset = (await call('media_import', { path: path.join(root, 'fixtures/media/clipA.mp4'), copyIntoProject: true })).asset;
  const tracks = (await call('timeline_inspect')).tracks, video = tracks.find((track) => track.kind === 'video'), audio = tracks.find((track) => track.kind === 'audio');
  child = spawn(electron, [path.join(root, 'packages/gui'), '--remote-debugging-port=' + debugPort, '--remote-debugging-address=127.0.0.1'], { cwd: root, env, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
  child.stdout.on('data', (data) => log += data); child.stderr.on('data', (data) => log += data);
  const target = await waitFor('Electron', async () => (await (await fetch(`http://127.0.0.1:${debugPort}/json/list`)).json()).find((target) => target.type === 'page' && target.url.includes('renderer/index.html')));
  socket = new WebSocket(target.webSocketDebuggerUrl); await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; });
  let id = 0; const pending = new Map();
  socket.onmessage = ({ data }) => { const message = JSON.parse(data); if (message.method === 'Runtime.exceptionThrown') errors.push(message.params.exceptionDetails.exception?.description ?? message.params.exceptionDetails.text); pending.get(message.id)?.(message); };
  const send = (method, params = {}) => new Promise((resolve, reject) => { const key = ++id, timer = setTimeout(() => { pending.delete(key); reject(new Error('CDP timeout: ' + method)); }, 20000); pending.set(key, (message) => { clearTimeout(timer); pending.delete(key); message.error ? reject(new Error(message.error.message)) : resolve(message.result); }); socket.send(JSON.stringify({ id: key, method, params })); });
  await send('Runtime.enable'); await send('Page.enable');
  const evaluate = async (expression) => { const result = await send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (result.exceptionDetails) throw new Error(result.exceptionDetails.exception?.description ?? result.exceptionDetails.text); return result.result.value; };
  const click = async (selector) => {
    await waitFor('GUI ready for ' + selector, async () => {
      const revision = (await (await fetch(bridge + '/state')).json()).revision;
      return evaluate(`Number(document.querySelector('#revision').textContent.replace('rev ',''))===${revision}&&!!document.querySelector(${JSON.stringify(selector)})&&!document.querySelector(${JSON.stringify(selector)}).disabled`);
    });
    await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
  };
  const input = (selector, value) => evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  const state = async () => (await (await fetch(bridge + '/state')).json()).project;
  const pairs = async () => (await state()).timeline.clipLinks ?? [];
  const find = async (clipId) => (await state()).timeline.tracks.flatMap((track) => track.clips).find((clip) => clip.id === clipId);
  const point = (trackId, time) => evaluate(`(()=>{const c=document.querySelector('#timeline'),r=c.getBoundingClientRect(),s=document.querySelector('#timeline-scroll'),rows=[...document.querySelectorAll('#track-headers .track-header')];return {x:r.left+${time}*Number(c.dataset.pps)-s.scrollLeft,y:r.top+Number(c.dataset.rulerHeight)+rows.findIndex(row=>row.dataset.trackId===${JSON.stringify(trackId)})*Number(c.dataset.trackHeight)+35-s.scrollTop}})()`);
  const gesture = async (trackId, time, delta = 0) => { const from = await point(trackId, time), to = await point(trackId, time + delta); await send('Input.dispatchMouseEvent', { type: 'mousePressed', ...from, button: 'left', clickCount: 1 }); if (delta) await send('Input.dispatchMouseEvent', { type: 'mouseMoved', ...to, button: 'left', buttons: 1 }); await send('Input.dispatchMouseEvent', { type: 'mouseReleased', ...to, button: 'left', clickCount: 1 }); };
  await waitFor('bin', () => evaluate(`!!document.querySelector('.media-item[data-asset-id="${asset.id}"]')`));
  assert.equal(await evaluate(`(()=>{const height=Number(document.querySelector('#timeline').dataset.trackHeight);return [...document.querySelectorAll('.track-header')].every(row=>{const bounds=row.getBoundingClientRect();return Math.abs(bounds.height-height)<1&&[...row.querySelectorAll('button')].every(button=>{const b=button.getBoundingClientRect();return b.bottom<=bounds.bottom&&b.right<=bounds.right})})})()`), true, 'headers and controls must fit the painted timeline rows');
  await evaluate(`document.querySelector('.media-item[data-asset-id="${asset.id}"]').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}))`);
  await input('#source-scrub', 1000 / asset.duration); await click('#source-in');
  await input('#source-scrub', 3000 / asset.duration); await click('#source-out');
  await input('#source-track', video.id); await click('#source-place');
  await waitFor('paired GUI source placement', async () => (await pairs()).length === 1);
  let pair = (await pairs())[0];
  assert.equal((await find(pair.videoClipId)).sourceIn, 1); assert.equal((await find(pair.audioClipId)).sourceIn, 1);
  await waitFor('visible linked highlight and waveform', () => evaluate(`document.querySelector('#timeline').dataset.selectedLinkedClips==='2'&&Number(document.querySelector('#timeline').dataset.waveformPeaks)>0&&document.querySelector('#btn-link-toggle').textContent.includes('Unlink')`));
  check('Source places linked picture/sound by default with waveform and both members highlighted');
  await click('#btn-snap');
  await gesture(audio.id, .5, 1);
  await waitFor('move either member', async () => (await find(pair.videoClipId)).start === 1 && (await find(pair.audioClipId)).start === 1);
  await click('#btn-undo'); await waitFor('single undo pair', async () => (await find(pair.videoClipId)).start === 0 && (await find(pair.audioClipId)).start === 0);
  await click('#btn-redo'); await waitFor('single redo pair', async () => (await find(pair.videoClipId)).start === 1);
  check('Dragging sound moves both clips; one undo/redo restores both');
  await gesture(audio.id, 1.5); await click('[data-workspace="audio"]');
  await input('#timecode-input', '00:00:01:15');
  await waitFor('decoded synchronized AV', () => evaluate(`(()=>{const v=document.querySelector('#preview-stage video'),a=document.querySelector('#preview-stage audio');return v?.readyState>=2&&a?.readyState>=2&&v.muted&&Math.abs(v.currentTime-a.currentTime)<.05&&Math.abs(v.currentTime-1.5)<.05})()`));
  await click('#btn-play');
  await waitFor('audible decoded audio meter', () => evaluate(`(()=>{const text=document.querySelector('#audio-meter-label')?.textContent;const db=Number(/RMS (-?[0-9.]+)/.exec(text??'')?.[1]);return Number.isFinite(db)&&db>-40&&document.querySelector('#preview-stage audio')?.paused===false})()`));
  await click('#btn-play');
  check('Actual Electron decodes both source windows in sync and Web Audio measures audible output');
  await click('[data-workspace="edit"]');
  await click(`[data-track-lock="${audio.id}"]`);
  await waitFor('locked audio', async () => (await state()).timeline.tracks.find((track) => track.id === audio.id).locked);
  const before = JSON.stringify((await state()).timeline);
  await gesture(video.id, 1.5, .5);
  await waitFor('clear lock refusal', () => evaluate(`document.querySelector('#toast').textContent.includes('locked')`));
  assert.equal(JSON.stringify((await state()).timeline), before);
  await input('#source-track', video.id); await input('#source-placement', 'append'); await click('#source-place');
  await waitFor('no silent video-only fallback', () => evaluate(`document.querySelector('#toast').textContent.includes('Add or unlock an audio track')`));
  assert.equal(JSON.stringify((await state()).timeline), before);
  await input('#source-placement', 'strict');
  await click(`[data-track-lock="${audio.id}"]`);
  await waitFor('unlock audio', async () => !(await state()).timeline.tracks.find((track) => track.id === audio.id).locked);
  check('A locked partner refuses a GUI edit without moving either clip');
  await gesture(video.id, 1.5); await click('#btn-link-toggle'); await waitFor('unlink GUI', async () => (await pairs()).length === 0 && await evaluate(`document.querySelector('#btn-link-toggle').textContent==='Link video + audio'`));
  await click('#btn-link-toggle'); await waitFor('relink GUI', async () => (await pairs()).length === 1 && await evaluate(`document.querySelector('#btn-link-toggle').textContent.includes('Unlink')`));
  await click('[data-tool="razor"]'); await gesture(video.id, 2);
  await waitFor('split pair', async () => (await pairs()).length === 2);
  await click('[data-tool="select"]');
  const second = (await pairs()).find((link) => link.videoClipId !== pair.videoClipId);
  await gesture(audio.id, 2.5); await click('#btn-delete'); await waitFor('delete pair', async () => !(await find(second.videoClipId)) && !(await find(second.audioClipId)));
  await click('#btn-undo'); await waitFor('undo delete pair', async () => !!(await find(second.videoClipId)) && !!(await find(second.audioClipId)));
  check('Visible unlink/relink, razor cut and delete preserve paired timing and undo');
  await gesture(audio.id, 2.99, -.2);
  await waitFor('paired GUI tail trim', async () => Math.abs((await find(second.videoClipId)).duration - .8) < 1e-6 && Math.abs((await find(second.audioClipId)).duration - .8) < 1e-6);
  await click('#btn-undo'); await waitFor('undo tail trim', async () => (await find(second.audioClipId)).duration === 1);
  await click('[data-tool="slip"]'); await gesture(audio.id, 2.5, .2);
  await waitFor('paired GUI slip', async () => Math.abs((await find(second.videoClipId)).sourceIn - 2.2) < 1e-6 && Math.abs((await find(second.audioClipId)).sourceIn - 2.2) < 1e-6);
  await click('#btn-undo'); await waitFor('undo slip', async () => (await find(second.audioClipId)).sourceIn === 2);
  await click('[data-tool="roll"]'); await gesture(video.id, 1.5, .2);
  await waitFor('paired GUI rolling cut', async () => Math.abs((await find(second.videoClipId)).start - 2.2) < 1e-6 && Math.abs((await find(second.audioClipId)).start - 2.2) < 1e-6);
  await click('#btn-undo'); await waitFor('undo roll', async () => (await find(second.audioClipId)).start === 2);
  await click('[data-tool="select"]'); await gesture(audio.id, 2.5); await click('#btn-duplicate');
  await waitFor('paired GUI duplicate', async () => (await pairs()).length === 3);
  await click('#btn-undo'); await waitFor('undo duplicate', async () => (await pairs()).length === 2);
  check('GUI trim, slip, rolling trim and duplicate keep picture/sound paired and undo together');
  await click('#btn-save'); await waitFor('GUI portable save', async () => JSON.parse(await fs.readFile(path.join(saved, 'project.json'), 'utf8')).timeline.clipLinks.length === 2);
  await call('clip_remove', { clipId: second.audioClipId });
  await click('#btn-open');
  await waitFor('guarded replacement prompt', () => evaluate(`document.querySelector('#protection-replace-dialog')?.open===true`));
  await evaluate(`document.querySelector('#protection-replace-discard').click()`);
  await waitFor('GUI reopen', async () => (await pairs()).length === 2);
  assert.equal((await call('media_waveform', { assetId: asset.id })).peaks.length > 0, true);
  const waveform = await fetch(bridge + '/waveform', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ assetId: asset.id }) }).then((response) => response.json());
  assert.equal(waveform.ok, true); assert.ok(waveform.peaks.some((peak) => peak > 0));
  check('GUI saves/reopens paired copied media; MCP and bridge waveform paths remain valid');
  await input('#timecode-input', '00:00:01:15');
  await waitFor('reopened decoders', () => evaluate(`document.querySelector('#preview-stage video')?.readyState>=2&&document.querySelector('#preview-stage audio')?.readyState>=2`));
  await click('#btn-export');
  await waitFor('GUI real export', () => evaluate(`!document.querySelector('#btn-export').disabled&&document.querySelector('#toast').textContent.startsWith('Exported')`), 120000);
  const { stdout: pcm } = await execute(process.env.FREEMIER_FFMPEG ?? 'ffmpeg', ['-v', 'error', '-i', output, '-map', '0:a:0', '-ac', '1', '-ar', '48000', '-f', 'f32le', 'pipe:1'], { encoding: 'buffer', windowsHide: true, maxBuffer: 4 * 1024 * 1024 });
  const samples = new Float32Array(pcm.buffer.slice(pcm.byteOffset, pcm.byteOffset + pcm.byteLength));
  const rms = (start, end) => { const values = samples.slice(start * 48000, end * 48000); return Math.sqrt(values.reduce((sum, value) => sum + value * value, 0) / values.length); };
  assert.ok(rms(.2, .7) < .001); assert.ok(rms(1.2, 1.7) > .03);
  await execute(process.env.FREEMIER_FFMPEG ?? 'ffmpeg', ['-v', 'error', '-i', output, '-map', '0:v:0', '-f', 'null', '-'], { windowsHide: true });
  check('GUI export fully decodes video and sound with a silent gap and audible edited range');
  // Dropping AV onto the timeline follows the same pair placement path; video-only is explicit.
  const drop = await point(video.id, 4);
  await evaluate(`(()=>{const transfer=new DataTransfer();transfer.setData('application/x-freemier-asset',${JSON.stringify(asset.id)});document.querySelector('#timeline').dispatchEvent(new DragEvent('drop',{bubbles:true,clientX:${drop.x},clientY:${drop.y},dataTransfer:transfer}))})()`);
  await waitFor('paired drag/drop', async () => (await pairs()).length === 3);
  await click('#btn-undo'); await waitFor('undo paired drop', async () => (await pairs()).length === 2);
  await input('#source-media-mode', 'video');
  await input('#source-track', video.id);
  await input('#source-placement', 'append'); await click('#source-place');
  await waitFor('explicit video-only', async () => (await state()).timeline.tracks.find((track) => track.id === video.id).clips.length === 3);
  assert.equal((await pairs()).length, 2); assert.equal((await state()).timeline.tracks.find((track) => track.id === audio.id).clips.length, 2);
  check('Timeline drop creates a pair; explicit Video only creates one independent clip');
  const unlinkedVideo = (await state()).timeline.tracks.find((track) => track.id === video.id).clips.find((clip) => clip.start === 3);
  const extraAudio = (await call('track_add', { kind: 'audio', name: 'Alternate sound' })).track;
  const common = { assetId: asset.id, start: 3, sourceIn: 1, duration: 2, strict: true };
  await call('clip_add', { ...common, trackId: audio.id });
  const alternate = (await call('clip_add', { ...common, trackId: extraAudio.id })).clip;
  await waitFor('extra audio painted', () => evaluate(`!!document.querySelector('[data-track-id="${extraAudio.id}"]')`));
  await gesture(video.id, 3.5); await click('#btn-link-toggle');
  await waitFor('matching clip chooser', () => evaluate(`document.querySelector('#clip-link-dialog').open&&document.querySelector('#clip-link-partner').options.length===2`));
  await click('#clip-link-dialog button[value="cancel"]'); assert.equal((await pairs()).length, 2);
  await click('#btn-link-toggle'); await waitFor('matching clip chooser reopened', () => evaluate(`document.querySelector('#clip-link-dialog').open`));
  await input('#clip-link-partner', alternate.id); await click('#clip-link-dialog button[value="link"]');
  await waitFor('chosen link', async () => (await pairs()).some((link) => link.videoClipId === unlinkedVideo.id && link.audioClipId === alternate.id));
  check('Ambiguous matches use a visible clip chooser; cancel preserves links and selection links the requested sound');
  assert.deepEqual(errors, []);
  console.log(`Linked media Electron acceptance: ${checks.length} checks passed.`);
} catch (error) { console.error(log); throw error; }
finally {
  socket?.close();
  if (child && child.exitCode === null) {
    if (process.platform === 'win32') await execute('taskkill', ['/PID', String(child.pid), '/T', '/F'], { windowsHide: true }).catch(() => {}); else child.kill();
    await Promise.race([new Promise((resolve) => child.once('exit', resolve)), sleep(4000)]);
  }
  await client?.close();
  if (!path.resolve(workspace).startsWith(path.join(root, '.tmp') + path.sep)) throw new Error('Unsafe fixture cleanup');
  await fs.rm(workspace, { recursive: true, force: true });
}
