/**
 * Core domain types for the FreeMier Pro editor.
 *
 * Design rules:
 *  - Every type is JSON-serializable without loss (no Date, Map, Set, class instances).
 *  - Time is always in SECONDS as a number. Frame math uses an explicit fps.
 *  - IDs are opaque strings, generated by the caller (see ids.ts).
 *  - All types are readonly at the field level to keep snapshots safe.
 */

/** Opaque identifier. Never assume format; always treat as a string. */
export type Id = string;

/** Persisted expected bytes, independent of transient file availability. */
export interface MediaSourceIdentity {
  readonly sha256: string;
  readonly size: number;
}

export type SourceIdentity = MediaSourceIdentity;

/** Ordinary project bin; null denotes the implicit library root. */
export interface MediaBin {
  readonly id: Id;
  readonly name: string;
  readonly parentId: Id | null;
}

/** Project-only metadata; importing or editing it never changes source files. */
export interface MediaLibraryEntry {
  readonly assetId: Id;
  readonly binId: Id | null;
  readonly description: string;
  readonly tags: readonly string[];
  readonly rating: number;
}

export interface MediaLibrary {
  readonly version: 1;
  readonly bins: readonly MediaBin[];
  readonly entries: readonly MediaLibraryEntry[];
}

/** A media file that has been imported into a project. */
export interface MediaAsset {
  readonly id: Id;
  /** Path relative to the project directory when copied, else absolute. */
  readonly path: string;
  /** True when the file lives inside the project (copied), false when referenced. */
  readonly copied: boolean;
  readonly name: string;
  readonly kind: 'video' | 'audio' | 'image';
  /** Duration in seconds. Images use a nominal duration. */
  readonly duration: number;
  readonly width: number;
  readonly height: number;
  readonly fps: number;
  readonly hasAudio: boolean;
  readonly sampleRate: number | null;
  readonly videoCodec: string | null;
  readonly audioCodec: string | null;
  /** Probe result capture time (epoch ms) — informational only. */
  readonly probedAt: number;
  readonly sourceIdentity?: MediaSourceIdentity;
}

/** A keyframe on an animatable numeric property. */
export interface Keyframe {
  /** Time relative to the start of the owning clip, in seconds. */
  readonly time: number;
  readonly value: number;
  /** Interpolation from this keyframe to the next. */
  readonly easing: 'linear' | 'hold' | 'ease-in' | 'ease-out' | 'ease-in-out';
}

/** A single animatable numeric property. */
export interface AnimatableProperty {
  /** Static value, used when `keyframes` is empty. */
  readonly value: number;
  readonly keyframes: readonly Keyframe[];
}

/** Spatial + opacity transform for a video clip. */
export interface Transform {
  /** Horizontal offset in normalized output units (0 = centered, -1 = full width left). */
  readonly x: AnimatableProperty;
  /** Vertical offset in normalized output units. */
  readonly y: AnimatableProperty;
  /** Uniform scale. 1 = fit to output. */
  readonly scale: AnimatableProperty;
  readonly rotation: AnimatableProperty;
  readonly opacity: AnimatableProperty;
}

/** A non-destructive effect applied to a clip. */
export interface Effect {
  readonly id: Id;
  readonly type: string;
  readonly params: Readonly<Record<string, number | string | boolean>>;
  readonly enabled: boolean;
}

/** A clip placed on a track. */
export interface Clip {
  readonly id: Id;
  readonly assetId: Id;
  /** Where this clip starts on the timeline, in seconds from timeline zero. */
  readonly start: number;
  /** Playable length on the timeline, in seconds. */
  readonly duration: number;
  /** Seconds into the source media where playback begins. */
  readonly sourceIn: number;
  /** Seconds into the source media where playback ends. */
  readonly sourceOut: number;
  readonly transform: Transform;
  readonly effects: readonly Effect[];
  readonly label: string | null;
  /** Volume multiplier for audio-bearing clips. 1 = unity. */
  readonly volume: number;
}

/** A horizontal lane holding clips of a single kind. */
export interface Track {
  readonly id: Id;
  readonly kind: 'video' | 'audio';
  readonly name: string;
  readonly clips: readonly Clip[];
  readonly muted: boolean;
  readonly locked: boolean;
  /** Higher renders later (on top). */
  readonly order: number;
}

/** The edit timeline. */
export interface TimelineMarker {
  readonly id: Id;
  /** Fixed sequence time, quantized to the sequence frame grid. */
  readonly time: number;
  readonly label: string;
  readonly color: string;
  readonly notes: string;
}

/** An aligned video/audio pair from one audio-bearing video asset. */
export interface ClipLink {
  readonly id: Id;
  readonly videoClipId: Id;
  readonly audioClipId: Id;
}

export interface Timeline {
  readonly id: Id;
  readonly name: string;
  readonly fps: number;
  readonly width: number;
  readonly height: number;
  readonly tracks: readonly Track[];
  /** Optional in schema 1; each clip belongs to at most one aligned AV pair. */
  readonly clipLinks?: readonly ClipLink[];
  /** Optional in legacy schema-1 projects. Markers never extend render duration. */
  readonly markers?: readonly TimelineMarker[];
  /** Independent topmost overlays, ordered by creation. Optional in schema 1. */
  readonly titles?: readonly TitleOverlay[];
  /** Optional independent subtitle track. Cue times retain SRT millisecond precision. */
  readonly captions?: CaptionTrack;
}

export interface TextStyle {
  readonly fontId: 'noto-sans';
  /** Output pixels at sequence resolution. */
  readonly fontSize: number;
  readonly color: string;
  readonly outlineColor: string;
  readonly outlineWidth: number;
  readonly backgroundColor: string;
  readonly backgroundOpacity: number;
  readonly padding: number;
  readonly opacity: number;
  /** Normalized frame anchor, with explicit text-block alignment. */
  readonly x: number;
  readonly y: number;
  readonly align: 'left' | 'center' | 'right';
  readonly verticalAlign: 'top' | 'middle' | 'bottom';
  readonly lineSpacing: number;
}
export interface TitleOverlay {
  readonly id: Id;
  readonly text: string;
  /** Frame-quantized sequence seconds, [start,end). */
  readonly start: number;
  readonly end: number;
  readonly style: TextStyle;
}

export interface CaptionCue {
  readonly id: Id;
  readonly text: string;
  /** Milliseconds in sequence time, half-open [startMs, endMs). */
  readonly startMs: number;
  readonly endMs: number;
}
export interface CaptionTrack {
  readonly id: Id;
  readonly name: string;
  readonly enabled: boolean;
  readonly locked: boolean;
  readonly style: TextStyle;
  readonly cues: readonly CaptionCue[];
}

/** A project: a timeline plus its media library. */
export interface Project {
  readonly id: Id;
  readonly name: string;
  /** Schema version, bumped when the on-disk shape changes. */
  readonly version: number;
  readonly timeline: Timeline;
  readonly media: readonly MediaAsset[];
  /** Optional in schema 1. Absence means root membership and default metadata. */
  readonly mediaLibrary?: MediaLibrary;
  /** Portable normalized effect presets, optional in schema-1 projects. */
  readonly effectPresets?: readonly import('../resources/presets.js').ImportedEffectPreset[];
  /** Created at epoch ms. */
  readonly createdAt: number;
  /** Last mutation at epoch ms. */
  readonly updatedAt: number;
}

/** Current on-disk schema version. */
export const PROJECT_SCHEMA_VERSION = 1;

/** Default transform for a newly created clip. */
export function defaultTransform(): Transform {
  const staticProp = (value: number): AnimatableProperty => ({ value, keyframes: [] });
  return {
    x: staticProp(0),
    y: staticProp(0),
    scale: staticProp(1),
    rotation: staticProp(0),
    opacity: staticProp(1),
  };
}
