import { registerComponentsControls } from '../components/controls.js';
import { registerConnectionClient } from '../connection/client.js';
import { registerPanelsAudioAudio } from '../panels/audio/audio.js';
import { registerPanelsCaptionsCaptions } from '../panels/captions/captions.js';
import { registerPanelsEffectControlsInspector } from '../panels/effect-controls/inspector.js';
import { registerPanelsExportExport } from '../panels/export/export.js';
import { registerPanelsKeyframesKeyframes } from '../panels/keyframes/keyframes.js';
import { registerPanelsMarkersMarkers } from '../panels/markers/markers.js';
import { registerPanelsPresetsPresets } from '../panels/presets/presets.js';
import { registerPanelsProgramMonitorProgram } from '../panels/program-monitor/program.js';
import { registerPanelsProjectBrowser } from '../panels/project/browser.js';
import { registerPanelsSourceMonitorSource } from '../panels/source-monitor/source.js';
import { registerPanelsTimelineTimeline } from '../panels/timeline/timeline.js';
import { registerPanelsTitlesTitles } from '../panels/titles/titles.js';
import { registerPanelsTransitionsTransitions } from '../panels/transitions/transitions.js';
import '../styles/app.css';
import { registerWorkspaceProjects } from '../workspace/projects.js';
import { registerWorkspaceTransport } from '../workspace/transport.js';
import { bindWorkspaceEvents } from './events.js';
import { createViewState } from './state.js';
import { registerAudioControls } from '../panels/audio/audio.js';
import { registerColorControls } from '../panels/color/color.js';
import { registerEffectBrowser } from '../panels/effect-browser/browser.js';
import { registerKeyframeControls } from '../panels/keyframes/keyframes.js';

const ui = createViewState();
registerComponentsControls(ui);
registerConnectionClient(ui);
registerWorkspaceTransport(ui);
registerWorkspaceProjects(ui);
registerPanelsProjectBrowser(ui);
registerPanelsPresetsPresets(ui);
registerPanelsTitlesTitles(ui);
registerPanelsCaptionsCaptions(ui);
registerPanelsMarkersMarkers(ui);
registerPanelsSourceMonitorSource(ui);
registerPanelsAudioAudio(ui);
registerPanelsProgramMonitorProgram(ui);
registerPanelsEffectControlsInspector(ui);
registerPanelsKeyframesKeyframes(ui);
registerPanelsTimelineTimeline(ui);
registerPanelsTransitionsTransitions(ui);
registerPanelsExportExport(ui);
registerEffectBrowser(ui);
registerKeyframeControls(ui);
registerAudioControls(ui);
registerColorControls(ui);
bindWorkspaceEvents(ui);
requestAnimationFrame(ui.tick);
void ui.boot();
