import { z } from 'zod';
import { addMarker, updateMarker, removeMarker, listMarkers } from '@freemier/engine';
import type { MarkerInput, MarkerPatch } from '@freemier/engine';
import type { ToolDef } from './tools.js';
const fields = { time: z.number().finite().min(0).max(86400), label: z.string().min(1).max(120), color: z.string().regex(/^#[0-9a-f]{6}$/i).optional(), notes: z.string().max(4096).optional() };
export const MARKER_TOOLS: ToolDef[] = [
  { name: 'marker_add', title: 'Add sequence marker', description: 'Add a fixed sequence-time point, rounded to the sequence frame grid. Markers never extend export duration or shift with current clip ripple edits.', inputSchema: fields, handler: async (a, c) => { const marker = addMarker(c.store, a as MarkerInput); return { ok: true, marker, frame: Math.round(marker.time * c.store.project.timeline.fps) }; } },
  { name: 'marker_update', title: 'Edit sequence marker', description: 'Update time, label, RGB color or plain notes in one undoable mutation. Invalid changes leave project and history unchanged.', inputSchema: { markerId: z.string(), time: fields.time.optional(), label: fields.label.optional(), color: fields.color, notes: fields.notes }, handler: async (a, c) => { const marker = updateMarker(c.store, a.markerId as string, a as MarkerPatch); return { ok: true, marker, frame: Math.round(marker.time * c.store.project.timeline.fps) }; } },
  { name: 'marker_remove', title: 'Remove sequence marker', description: 'Remove a marker by stable ID in one normal project history item.', inputSchema: { markerId: z.string() }, handler: async (a, c) => { removeMarker(c.store, a.markerId as string); return { ok: true, removed: a.markerId }; } },
  { name: 'marker_list', title: 'Query sequence markers', description: 'Read markers sorted by sequence time in an optional half-open [start,end) range. Returns resolved frame numbers.', inputSchema: { start: z.number().finite().min(0).optional(), end: z.number().finite().min(0).optional() }, handler: async (a, c) => ({ ok: true, markers: listMarkers(c.store, a.start as number | undefined, a.end as number | undefined).map((m) => ({ ...m, frame: Math.round(m.time * c.store.project.timeline.fps) })), timeDomain: 'sequence seconds', ripplePolicy: 'fixed', affectsRenderDuration: false }) },
];
