import { z } from 'zod';
import { slipClip, rollClips, duplicateClip, setKeyframe, removeKeyframe, addEffect, updateEffect, removeEffect, findClip } from '@freemier/engine';
import { EFFECT_CATALOG, TRANSFORM_LIMITS, EASINGS, EditorError, type TransformProperty } from '@freemier/shared';
import type { ToolDef } from './tools.js';

const property = z.enum(['x', 'y', 'scale', 'rotation', 'opacity']);
const params = z.record(z.union([z.number().finite(), z.string(), z.boolean()]));
const clipId = z.string();
const ok = (data: Record<string, unknown>) => ({ ok: true, ...data });
export const PROFESSIONAL_TOOLS: ToolDef[] = [
  { name: 'clip_slip', title: 'Slip source window', description: 'Shift the source in/out together without changing timeline position or duration. Delta is frame aligned and source bounded.', inputSchema: { clipId, delta: z.number().finite() }, handler: async (a, c) => ok({ clip: slipClip(c.store, a.clipId as string, a.delta as number) }) },
  { name: 'clip_roll', title: 'Roll adjacent edit', description: 'Move the shared boundary of adjacent clips, keeping their outer timeline endpoints fixed. Atomic and source bounded. Animated right-hand clips require clearing curves/fades first.', inputSchema: { leftClipId: z.string(), rightClipId: z.string(), at: z.number().finite().min(0) }, handler: async (a, c) => { const [left, right] = rollClips(c.store, a.leftClipId as string, a.rightClipId as string, a.at as number); return ok({ left, right }); } },
  { name: 'clip_duplicate', title: 'Duplicate clip', description: 'Deep-copy a clip, transforms and effects into an unoccupied range. Default position is immediately after the original.', inputSchema: { clipId, start: z.number().finite().min(0).optional(), trackId: z.string().optional() }, handler: async (a, c) => ok({ clip: duplicateClip(c.store, a.clipId as string, a.start as number | undefined, a.trackId as string | undefined) }) },
  { name: 'keyframe_set', title: 'Set transform keyframe', description: 'Upsert a frame-aligned clip-local transform keyframe. The preceding key owns easing into the next key; values clamp before/after the curve. One undo step.', inputSchema: { clipId, property, time: z.number().finite().min(0), value: z.number().finite(), easing: z.enum(EASINGS).optional() }, handler: async (a, c) => ok({ clip: setKeyframe(c.store, a.clipId as string, a.property as TransformProperty, a.time as number, a.value as number, a.easing as typeof EASINGS[number] | undefined) }) },
  { name: 'keyframe_remove', title: 'Remove transform keyframe', description: 'Remove a key at a frame-aligned local time. Removing the last key restores the static property value.', inputSchema: { clipId, property, time: z.number().finite().min(0) }, handler: async (a, c) => ok({ clip: removeKeyframe(c.store, a.clipId as string, a.property as TransformProperty, a.time as number) }) },
  { name: 'keyframe_list', title: 'Inspect transform curves', description: 'Read every transform curve, or one property, including static values and local-time keys.', inputSchema: { clipId, property: property.optional() }, handler: async (a, c) => { const found = findClip(c.store.project.timeline, a.clipId as string); if (!found) throw new EditorError('NOT_FOUND', 'Clip not found'); return ok({ transform: a.property ? { [a.property as string]: found.clip.transform[a.property as TransformProperty] } : found.clip.transform }); } },
  { name: 'effect_add', title: 'Add effect', description: 'Append an enabled effect from effect_catalog. Params are strictly validated; effects run in stored order. Video/audio effects require the matching track kind.', inputSchema: { clipId, type: z.string(), params: params.optional() }, handler: async (a, c) => ok({ effect: addEffect(c.store, a.clipId as string, a.type as string, a.params as Record<string, number | string | boolean> | undefined) }) },
  { name: 'effect_update', title: 'Update effect', description: 'Merge validated params and/or enable an effect. One undo step; no mutation on validation failure.', inputSchema: { clipId, effectId: z.string(), params: params.optional(), enabled: z.boolean().optional() }, handler: async (a, c) => ok({ effect: updateEffect(c.store, a.clipId as string, a.effectId as string, a.params as Record<string, number | string | boolean> | undefined, a.enabled as boolean | undefined) }) },
  { name: 'effect_remove', title: 'Remove effect', description: 'Remove one effect by id.', inputSchema: { clipId, effectId: z.string() }, handler: async (a, c) => ok({ clip: removeEffect(c.store, a.clipId as string, a.effectId as string) }) },
  { name: 'effect_list', title: 'Inspect ordered effects', description: 'Read a clip effect stack, including disabled entries.', inputSchema: { clipId }, handler: async (a, c) => { const found = findClip(c.store.project.timeline, a.clipId as string); if (!found) throw new EditorError('NOT_FOUND', 'Clip not found'); return ok({ effects: found.clip.effects }); } },
  { name: 'effect_catalog', title: 'Effect catalog', description: 'Read supported CPU export effects, bounded schemas and preview implementation requirements.', inputSchema: {}, handler: async () => ok({ effects: EFFECT_CATALOG }) },
  { name: 'editor_capabilities', title: 'Editor capabilities', description: 'Read implemented and unsupported capabilities; availability does not imply pixel-identical live preview.', inputSchema: {}, handler: async () => ok({ version: '0.2.0', editing: ['move', 'ripple_move', 'split', 'trim', 'slip', 'roll', 'duplicate', 'track_mute', 'track_lock', 'undo', 'redo'], animation: { properties: TRANSFORM_LIMITS, easing: EASINGS, time: 'clip-local seconds', evaluation: 'preceding key owns outgoing segment', maxKeysPerProperty: 256, export: 'cpu' }, effects: EFFECT_CATALOG, annotations: { markers: { commands: ['marker_add', 'marker_update', 'marker_remove', 'marker_list'], maxCount: 4096, time: 'fixed sequence seconds rounded to frames', range: [0, 86400], ripplePolicy: 'fixed', affectsRenderDuration: false } }, composition: { titles: { commands: ['font_list', 'title_add', 'title_update', 'title_remove', 'title_list'], maxCount: 64, maxCharacters: 4096, maxLines: 16, time: 'fixed frame-quantized sequence [start,end)', affectsRenderDuration: true, order: 'creation order above video', renderer: 'CPU FFmpeg drawtext to shared RGBA PNG', font: 'bundled checksummed Noto Sans Regular, OFL-1.1', scripts: 'Latin/Greek/Cyrillic; other glyphs not guaranteed', maxRasterDimension: 8192, maxRasterPixels: 33554432, style: 'static plain text; integer font/outline/box/spacing pixels; normalized aligned anchor; RGB/opacity', animatedText: false, implicitFontFallback: false }, captions: { commands: ['caption_add', 'caption_update', 'caption_remove', 'captions_list', 'captions_import', 'captions_export', 'caption_track_update'], maxCount: 256, maxCharacters: 4096, maxLines: 16, trackCount: 1, time: 'integer milliseconds [startMs,endMs)', frameCoverage: 'sequence frame timestamps inside cue; jump selects first covered frame', overlaps: 'rejected', ripplePolicy: 'fixed', durationPolicy: 'authored cue extent rounded up to frames, independent of visibility/output policy', renderer: 'same CPU RGBA glyph path as titles, above titles', import: 'explicit SRT content, atomic append/replace', export: ['burn-in', 'none', 'sidecar'], style: 'shared static track style with bundled Noto Sans', locks: 'explicit unlock before edits', unsupported: ['WebVTT', 'ASS', 'multiple tracks', 'rich text', 'animated captions', 'automatic transcription'] } }, timecode: { format: 'non-drop HH:MM:SS:FF', fractionalRate: 'nominal frame counts divided by actual fps', dropFrame: false }, limitations: ['Origin-changing split/head trim/right-side roll reject clips with keyframes or enabled fades; equivalent curve rebasing is not implemented', 'Effect preview implementation requirements are reported per effect; this API does not assert preview/export parity'], unsupported: ['speed_ramp', 'optical_flow', 'tracking', 'stabilization', 'LUT', 'GPU_effect_export', 'nested_sequences', 'adjustment_layers', 'transitions'] }) },
];
